name: PHP

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      # Note: This workflow uses the latest stable version of the PHP.
      # You can specify other versions if desired, see documentation here:
      # https://github.com/shivammathur/setup-php/blob/master/README.md
      # - uses: shivammathur/setup-php@2.21.1
      - name: Setup PHP Action
        uses: shivammathur/setup-php@72ae4ccbe57f82bbe08411e84e2130bd4ba1c10f # 2.25.5

      - name: Verify formatting
        run: php -l main.php

      - name: Run
        run: php main.php
